max_width = 120
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"

edition = "2021"
force_explicit_abi = true
merge_derives = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
